RR-349 #time 1m ci: envs for auth0 were added

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -148,180 +148,180 @@ stages:
           artifact: bundle
 - stage: Test
   jobs:
-    # - job: UnitTesting1
-    #   displayName: "Unit Testing 1"
-    #   condition: and(or(contains(variables['build.SourceBranch'], 'feature'), contains(variables['build.SourceBranch'], 'bugfix'), contains(variables['build.SourceBranch'], 'hotfix')), succeeded())
-    #   pool:
-    #     vmImage: "ubuntu-latest"
-    #   steps:
-    #     - task: Cache@2
-    #       inputs:
-    #         key: 'admnpmV3 | "$(Agent.OS)" | package.json'
-    #         restoreKeys: |
-    #           admnpmV3 | "$(Agent.OS)"
-    #         path: "$(System.DefaultWorkingDirectory)/node_modules"
-    #         cacheHitVar: CACHE_RESTORED
-    #       displayName: Cache npm
-    #     - script: |
-    #         npm install --force
-    #       condition: ne(variables.CACHE_RESTORED, 'true')
-    #     - task: DownloadPipelineArtifact@2
-    #       name: environment
-    #       inputs:
-    #         artifact: Environment
-    #         targetPath: '$(System.DefaultWorkingDirectory)'
-    #     - task: DownloadPipelineArtifact@2
-    #       name: bundle
-    #       inputs:
-    #         artifact: bundle
-    #         targetPath: '$(System.DefaultWorkingDirectory)'
-    #     - script: |
-    #         npm install pm2@5.3.0 -g
-    #         source .env
-    #         npm install express --force
-    #         export NODE_OPTIONS=--max-old-space-size=8192
-    #         pm2 start scripts/server.js
-    #         node --version
-    #         sleep 5
-    #         # mkdir reports
-    #         # mkdir reports-xml
-    #         # npm install nyc --save-dev --force
-    #         # node scripts/bdd_unit_testing_azure.js
-    #         # if [ $? -ne 0 ]; then
-    #         #   echo "testing failed"
-    #         #   exit 1
-    #         # fi
-    #         echo "Completed tasks - exit $?"
-    #       displayName: Unit Testing
-    #     - publish: $(System.DefaultWorkingDirectory)/features/step-definations/failed_scenarios/ # Assuming logs are in working directory
-    #       artifact: '$(system.JobId)-failedScenarios'
-    #       condition: always()
-    #     - publish: $(System.DefaultWorkingDirectory)/features/step-definations/coverageData/ # Assuming logs are in working directory
-    #       artifact: '1-coverageData'
-    #     - publish: $(System.DefaultWorkingDirectory)/reports/ # Assuming logs are in working directory
-    #       artifact: '1-living-documentation'
-    #     - task: PublishTestResults@2
-    #       condition: always()
-    #       inputs:
-    #         testResultsFormat: 'JUnit'
-    #         testResultsFiles: '**/TEST-*.xml'
-    #     - task: PublishCodeCoverageResults@1
-    #       condition: always()
-    #       inputs:
-    #         codeCoverageTool: 'Cobertura'
-    #         summaryFileLocation: 'coverage-cobertura/cobertura-coverage.xml'
+    - job: UnitTesting1
+      displayName: "Unit Testing 1"
+      condition: and(or(contains(variables['build.SourceBranch'], 'feature'), contains(variables['build.SourceBranch'], 'bugfix'), contains(variables['build.SourceBranch'], 'hotfix')), succeeded())
+      pool:
+        vmImage: "ubuntu-latest"
+      steps:
+        - task: Cache@2
+          inputs:
+            key: 'admnpmV3 | "$(Agent.OS)" | package.json'
+            restoreKeys: |
+              admnpmV3 | "$(Agent.OS)"
+            path: "$(System.DefaultWorkingDirectory)/node_modules"
+            cacheHitVar: CACHE_RESTORED
+          displayName: Cache npm
+        - script: |
+            npm install --force
+          condition: ne(variables.CACHE_RESTORED, 'true')
+        - task: DownloadPipelineArtifact@2
+          name: environment
+          inputs:
+            artifact: Environment
+            targetPath: '$(System.DefaultWorkingDirectory)'
+        - task: DownloadPipelineArtifact@2
+          name: bundle
+          inputs:
+            artifact: bundle
+            targetPath: '$(System.DefaultWorkingDirectory)'
+        - script: |
+            npm install pm2@5.3.0 -g
+            source .env
+            npm install express --force
+            export NODE_OPTIONS=--max-old-space-size=8192
+            pm2 start scripts/server.js
+            node --version
+            sleep 5
+            # mkdir reports
+            # mkdir reports-xml
+            # npm install nyc --save-dev --force
+            # node scripts/bdd_unit_testing_azure.js
+            # if [ $? -ne 0 ]; then
+            #   echo "testing failed"
+            #   exit 1
+            # fi
+            echo "Completed tasks - exit $?"
+          displayName: Unit Testing
+        - publish: $(System.DefaultWorkingDirectory)/features/step-definations/failed_scenarios/ # Assuming logs are in working directory
+          artifact: '$(system.JobId)-failedScenarios'
+          condition: always()
+        - publish: $(System.DefaultWorkingDirectory)/features/step-definations/coverageData/ # Assuming logs are in working directory
+          artifact: '1-coverageData'
+        - publish: $(System.DefaultWorkingDirectory)/reports/ # Assuming logs are in working directory
+          artifact: '1-living-documentation'
+        - task: PublishTestResults@2
+          condition: always()
+          inputs:
+            testResultsFormat: 'JUnit'
+            testResultsFiles: '**/TEST-*.xml'
+        - task: PublishCodeCoverageResults@1
+          condition: always()
+          inputs:
+            codeCoverageTool: 'Cobertura'
+            summaryFileLocation: 'coverage-cobertura/cobertura-coverage.xml'
     
-    # - job: Reports
-    #   displayName: "Testing Reports"
-    #   dependsOn:
-    #     - UnitTesting1
-    #   condition: and(or(contains(variables['build.SourceBranch'], 'feature'), contains(variables['build.SourceBranch'], 'bugfix'), contains(variables['build.SourceBranch'], 'hotfix')), succeeded())
-    #   pool:
-    #     vmImage: "ubuntu-latest"
-    #   steps:
-    #     - task: Cache@2
-    #       inputs:
-    #         key: 'admnpmV3 | "$(Agent.OS)" | package.json'
-    #         restoreKeys: |
-    #           admnpmV3 | "$(Agent.OS)"
-    #         path: "$(System.DefaultWorkingDirectory)/node_modules"
-    #         cacheHitVar: CACHE_RESTORED
-    #       displayName: Cache npm
-    #     - script: |
-    #         npm install --force
-    #       condition: ne(variables.CACHE_RESTORED, 'true')
-    #     - task: DownloadPipelineArtifact@2
-    #       name: environment
-    #       inputs:
-    #         artifact: Environment
-    #         targetPath: '$(System.DefaultWorkingDirectory)'
-    #     - task: DownloadPipelineArtifact@2
-    #       name: LivingDoc1
-    #       inputs:
-    #         artifactName: '1-living-documentation'
-    #         targetPath: '$(System.DefaultWorkingDirectory)/reports'
-    #       displayName: 'Download Living Documentation Artifact'
-    #     - task: DownloadPipelineArtifact@2
-    #       name: Coverage1
-    #       inputs:
-    #         artifactName: '1-coverageData'
-    #         targetPath: '$(System.DefaultWorkingDirectory)/features/step-definations/coverageData'
-    #       displayName: 'Download coverage Documentation Artifact'
-    #     - script: |
-    #         echo "##vso[task.setvariable variable=RepositoryName]$BUILD_REPOSITORY_NAME"
-    #         echo "##vso[task.setvariable variable=SourceBranch]$SourceBranch"
-    #         source .env
-    #         npm install nyc --save-dev --force
-    #         mkdir coverage
-    #         npm run generate_report
-    #         node scripts/livingdoc.js 
-    #         ls -R reports
-    #         export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_MAIN}
-    #         export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_MAIN}
-    #         aws s3 sync coverage s3://$S3_BUCKET_NAME/coverage-admin --acl public-read
-    #         aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID_DOCS --paths "/*"
-    #         aws s3 sync living-documentation s3://$S3_BUCKET_NAME/living-documentation-admin-web-application --acl public-read
-    #         aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID_DOCS --paths "/*"
-    #       displayName: 'BDD Coverage'
-    #       condition: always()
+    - job: Reports
+      displayName: "Testing Reports"
+      dependsOn:
+        - UnitTesting1
+      condition: and(or(contains(variables['build.SourceBranch'], 'feature'), contains(variables['build.SourceBranch'], 'bugfix'), contains(variables['build.SourceBranch'], 'hotfix')), succeeded())
+      pool:
+        vmImage: "ubuntu-latest"
+      steps:
+        - task: Cache@2
+          inputs:
+            key: 'admnpmV3 | "$(Agent.OS)" | package.json'
+            restoreKeys: |
+              admnpmV3 | "$(Agent.OS)"
+            path: "$(System.DefaultWorkingDirectory)/node_modules"
+            cacheHitVar: CACHE_RESTORED
+          displayName: Cache npm
+        - script: |
+            npm install --force
+          condition: ne(variables.CACHE_RESTORED, 'true')
+        - task: DownloadPipelineArtifact@2
+          name: environment
+          inputs:
+            artifact: Environment
+            targetPath: '$(System.DefaultWorkingDirectory)'
+        - task: DownloadPipelineArtifact@2
+          name: LivingDoc1
+          inputs:
+            artifactName: '1-living-documentation'
+            targetPath: '$(System.DefaultWorkingDirectory)/reports'
+          displayName: 'Download Living Documentation Artifact'
+        - task: DownloadPipelineArtifact@2
+          name: Coverage1
+          inputs:
+            artifactName: '1-coverageData'
+            targetPath: '$(System.DefaultWorkingDirectory)/features/step-definations/coverageData'
+          displayName: 'Download coverage Documentation Artifact'
+        - script: |
+            echo "##vso[task.setvariable variable=RepositoryName]$BUILD_REPOSITORY_NAME"
+            echo "##vso[task.setvariable variable=SourceBranch]$SourceBranch"
+            source .env
+            npm install nyc --save-dev --force
+            mkdir coverage
+            npm run generate_report
+            node scripts/livingdoc.js 
+            ls -R reports
+            export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_MAIN}
+            export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_MAIN}
+            aws s3 sync coverage s3://$S3_BUCKET_NAME/coverage-admin --acl public-read
+            aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID_DOCS --paths "/*"
+            aws s3 sync living-documentation s3://$S3_BUCKET_NAME/living-documentation-admin-web-application --acl public-read
+            aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID_DOCS --paths "/*"
+          displayName: 'BDD Coverage'
+          condition: always()
     
-    # - job: IntegrationTesting
-    #   displayName: "Integration Testing"
-    #   condition: and(succeeded(), contains(variables['build.SourceBranch'], 'qa'))
-    #   pool:
-    #     vmImage: "ubuntu-latest"
-    #   steps:
-    #     - task: Cache@2
-    #       inputs:
-    #         key: 'admnpmV3 | "$(Agent.OS)" | package.json'
-    #         restoreKeys: |
-    #           admnpmV3 | "$(Agent.OS)"
-    #         path: "$(System.DefaultWorkingDirectory)/node_modules"
-    #         cacheHitVar: CACHE_RESTORED
-    #       displayName: Cache npm
-    #     - script: |
-    #         npm install --force
-    #       condition: ne(variables.CACHE_RESTORED, 'true')
-    #     - task: DownloadPipelineArtifact@2
-    #       name: environment
-    #       inputs:
-    #         artifact: Environment
-    #         targetPath: '$(System.DefaultWorkingDirectory)'
-    #     - task: DownloadPipelineArtifact@2
-    #       name: bundle
-    #       inputs:
-    #         artifact: bundle
-    #         targetPath: '$(System.DefaultWorkingDirectory)'
-    #     - script: |
-    #         npm install -g pm2
-    #         source .env
-    #         export NODE_OPTIONS=--max-old-space-size=8192
-    #         npm install express --force
-    #         pm2 start scripts/server.js
-    #         sleep 60
-    #         mkdir -p reports/test-report-features
-    #         mkdir -p reports-xml
-    #         npm install nyc --save-dev --force
-    #         mkdir reports-xml
-    #         node scripts/integration_testing.js
-    #         if [ $? -ne 0 ]; then
-    #           echo "Integration Testing failed"
-    #           exit 1
-    #         fi
-    #       displayName: Integration Testing
-    #     - publish: $(System.DefaultWorkingDirectory)/features/step-definations/failed_scenarios/ # Assuming logs are in working directory
-    #       artifact: '$(system.JobId)-failedScenarios'
-    #       condition: always()
-    #     # - task: PublishCodeCoverageResults@1
-    #     #   condition: always()
-    #     #   inputs:
-    #     #     codeCoverageTool: 'Cobertura'
-    #     #     summaryFileLocation: 'coverage-cobertura/cobertura-coverage.xml'
-    #     - task: PublishTestResults@2
-    #       condition: always()
-    #       inputs:
-    #         testResultsFormat: 'JUnit'
-    #         testResultsFiles: '**/TEST-*.xml'
+    - job: IntegrationTesting
+      displayName: "Integration Testing"
+      condition: and(succeeded(), contains(variables['build.SourceBranch'], 'qa'))
+      pool:
+        vmImage: "ubuntu-latest"
+      steps:
+        - task: Cache@2
+          inputs:
+            key: 'admnpmV3 | "$(Agent.OS)" | package.json'
+            restoreKeys: |
+              admnpmV3 | "$(Agent.OS)"
+            path: "$(System.DefaultWorkingDirectory)/node_modules"
+            cacheHitVar: CACHE_RESTORED
+          displayName: Cache npm
+        - script: |
+            npm install --force
+          condition: ne(variables.CACHE_RESTORED, 'true')
+        - task: DownloadPipelineArtifact@2
+          name: environment
+          inputs:
+            artifact: Environment
+            targetPath: '$(System.DefaultWorkingDirectory)'
+        - task: DownloadPipelineArtifact@2
+          name: bundle
+          inputs:
+            artifact: bundle
+            targetPath: '$(System.DefaultWorkingDirectory)'
+        - script: |
+            npm install -g pm2
+            source .env
+            export NODE_OPTIONS=--max-old-space-size=8192
+            npm install express --force
+            pm2 start scripts/server.js
+            sleep 60
+            mkdir -p reports/test-report-features
+            mkdir -p reports-xml
+            npm install nyc --save-dev --force
+            mkdir reports-xml
+            node scripts/integration_testing.js
+            if [ $? -ne 0 ]; then
+              echo "Integration Testing failed"
+              exit 1
+            fi
+          displayName: Integration Testing
+        - publish: $(System.DefaultWorkingDirectory)/features/step-definations/failed_scenarios/ # Assuming logs are in working directory
+          artifact: '$(system.JobId)-failedScenarios'
+          condition: always()
+        # - task: PublishCodeCoverageResults@1
+        #   condition: always()
+        #   inputs:
+        #     codeCoverageTool: 'Cobertura'
+        #     summaryFileLocation: 'coverage-cobertura/cobertura-coverage.xml'
+        # - task: PublishTestResults@2
+        #   condition: always()
+        #   inputs:
+        #     testResultsFormat: 'JUnit'
+        #     testResultsFiles: '**/TEST-*.xml'
           
     - job: BrowserPerformanceTesting
       displayName: "Browser Performance Testing"
